INSERT INTO patientrisks`(PersonID`, Age, Diabetic, HistoryOfHeartDisease) 
VALUES ([1],[N],[N],[N])
INSERT INTO patientrisks`(PersonID`, Age, Diabetic, HistoryOfHeartDisease) 
VALUES ([2],[N],[Y],[N])
INSERT INTO patientrisks`(PersonID`, Age, Diabetic, HistoryOfHeartDisease)  
VALUES ([3],[N],[N],[N])
INSERT INTO patientrisks`(PersonID`, Age, Diabetic, HistoryOfHeartDisease) 
VALUES ([4],[Y],[N],[N])
INSERT INTO patientrisks`(PersonID`, Age, Diabetic, HistoryOfHeartDisease) 
VALUES ([5],[Y],[Y],[Y])
INSERT INTO patientrisks`(PersonID`, Age, Diabetic, HistoryOfHeartDisease) 
VALUES ([6],[N],[Y],[N])
INSERT INTO patientrisks`(PersonID`, Age, Diabetic, HistoryOfHeartDisease) 
VALUES ([7],[Y],[N],[N])
INSERT INTO patientrisks`(PersonID`, Age, Diabetic, HistoryOfHeartDisease) 
VALUES ([8],[Y],[N],[Y])
INSERT INTO patientrisks`(PersonID`, Age, Diabetic, HistoryOfHeartDisease)  
VALUES ([9],[Y],[Y],[N])
INSERT INTO patientrisks`(PersonID`, Age, Diabetic, HistoryOfHeartDisease)  
VALUES ([10],[Y],[N],[N])