INSERT INTO patientvitals`(PersonID`, Timestamp, PulseRate, SystolicBP, DiastolicBP, OxygenSaturation, Temperature, Notes) 
VALUES ([1],[CURRENT_TIMESTAMP],[50],[110],[83],[87],[96],[dizziness])
INSERT INTO patientvitals`(PersonID`, Timestamp, PulseRate, SystolicBP, DiastolicBP, OxygenSaturation, Temperature, Notes) 
75LUES ([2],[CURRENT_TIMESTAMP],[75],[100],[63],[93],[99],[chest pain])
INSERT INTO patientvitals`(PersonID`, Timestamp, PulseRate, SystolicBP, DiastolicBP, OxygenSaturation, Temperature, Notes) 
VALUES ([3],[CURRENT_TIMESTAMP],[83],[92],[76],[95],[98],[severe headache])
INSERT INTO patientvitals`(PersonID`, Timestamp, PulseRate, SystolicBP, DiastolicBP, OxygenSaturation, Temperature, Notes) 
VALUES ([4],[CURRENT_TIMESTAMP],[66],[97],[82],[92],[97],[syncope])
INSERT INTO patientvitals`(PersonID`, Timestamp, PulseRate, SystolicBP, DiastolicBP, OxygenSaturation, Temperature, Notes) 
VALUES ([5],[CURRENT_TIMESTAMP],[38],[65],[43],[86],[96],[unconscious, with chest pain])
INSERT INTO patientvitals`(PersonID`, Timestamp, PulseRate, SystolicBP, DiastolicBP, OxygenSaturation, Temperature, Notes) 
VALUES ([6],[CURRENT_TIMESTAMP],[76],[103],[95],[94],[103],[fever])
INSERT INTO patientvitals`(PersonID`, Timestamp, PulseRate, SystolicBP, DiastolicBP, OxygenSaturation, Temperature, Notes) 
VALUES ([7],[CURRENT_TIMESTAMP],[99],[92],[83],[93],[96],[syncope])
INSERT INTO patientvitals`(PersonID`, Timestamp, PulseRate, SystolicBP, DiastolicBP, OxygenSaturation, Temperature, Notes) 
VALUES ([8],[CURRENT_TIMESTAMP],[47],[164],[124],[94],[97],[dizziness, pot stroke])
INSERT INTO patientvitals`(PersonID`, Timestamp, PulseRate, SystolicBP, DiastolicBP, OxygenSaturation, Temperature, Notes) 
VALUES ([9],[CURRENT_TIMESTAMP],[34],[113],[92],[96],[97],[poisoning])
INSERT INTO patientvitals`(PersonID`, Timestamp, PulseRate, SystolicBP, DiastolicBP, OxygenSaturation, Temperature, Notes) 
VALUES ([10],[CURRENT_TIMESTAMP],[64],[90],[76],[91],[96],[chest pain])